"""Add thumbnail_url to ContentPiece

Revision ID: 4e0b6f020be8
Revises: 485d45cb7f4e
Create Date: 2026-07-08 21:23:00.705776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0b6f020be8'
down_revision: Union[str, Sequence[str], None] = '485d45cb7f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_pieces', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_pieces', 'thumbnail_url')
    # ### end Alembic commands ###
